name: Build cloudflared

on:
  workflow_dispatch:
    inputs:
      cloudflared_version:
        description: "Commit to build"
        required: true

jobs:
  bake-cloudflared-bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Generate metadata
        id: gen_meta
        run: |
          echo "${{ github.event.inputs.cloudflared_version }}"
          echo ::set-output name=cloudflared_ver::${{ github.event.inputs.cloudflared_version }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.1.0
        with:
          images: |
            ghcr.io/roxedus/pipelines
          labels: |
            org.opencontainers.image.title=cloudflared
            org.opencontainers.image.description="https://github.com/cloudflare/cloudflared"
            org.opencontainers.image.vendor=roxedus
            org.opencontainers.image.source="https://github.com/roxedus/pipelines"
            org.opencontainers.image.version="${{ steps.gen_meta.outputs.cloudflared_ver }}"
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.gen_meta.outputs.cloudflared_ver }}
          flavor: |
            prefix=cloudflared-,onlatest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: roxedus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v2.3.0
        with:
          set: "image.context=https://github.com/cloudflare/cloudflared.git#${{ steps.gen_meta.outputs.cloudflared_ver }}"
          files: |
            ./cloudflared-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: all
          push: true

      - name: Update version
        run: |
          echo "${{ steps.gen_meta.outputs.cloudflared_ver }}" > cloudflared_version.txt
          git config --global user.name 'rox'
          git config --global user.email 'roxedus@users.noreply.github.com'
          git add cloudflared_version.txt
          git commit -m "Automated bump"
          git push
