name: Check main

on:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - ".github/workflows/cloudflared-trigger.yml"
jobs:
  updates:
    name: Check latest version
    runs-on: ubuntu-latest
    steps:
      - name: Create VARS
        run: |
          export CLOUDFLARED_VERSION=$(curl -sX GET https://api.github.com/repos/cloudflare/cloudflared/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
          if  [[ $(< cloudflared_version.txt) != "${CLOUDFLARED_VERSION}" ]]; then
            curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/Roxedus/pipelines/actions/workflows/cloudflared-bake.yml/dispatches \
              -d "{\"ref\":\"refs/heads/main\", \"inputs\":{\"cloudflared_version\": \"${CLOUDFLARED_VERSION}\"}" \
              -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}"
          else
            echo "latest version ${CLOUDFLARED_VERSION} already built"
          fi
