name: Build Rallly

on:
  workflow_dispatch:
    inputs:
      rallly_version:
        description: "Commit to build"
        required: true

jobs:
  bake-rallly-bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Generate metadata
        id: gen_meta
        run: |
          echo "${{ github.event.inputs.rallly_version }}"
          echo ::set-output name=rallly_ver::${{ github.event.inputs.rallly_version }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: |
            ghcr.io/roxedus/pipelines
          labels: |
            org.opencontainers.image.title=rallly
            org.opencontainers.image.description="https://github.com/lukevella/rallly"
            org.opencontainers.image.vendor=roxedus
            org.opencontainers.image.source="https://github.com/roxedus/pipelines"
            org.opencontainers.image.version="${{ steps.gen_meta.outputs.rallly_ver }}"
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.gen_meta.outputs.rallly_ver }}
          flavor: |
            prefix=rallly-,onlatest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: roxedus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v5.11.0
        with:
          set: |
            image.context=https://github.com/lukevella/rallly.git#${{ steps.gen_meta.outputs.rallly_ver }}
            image.args.APP_VERSION=${{ steps.gen_meta.outputs.rallly_ver }}
            image.args.SELF_HOSTED=true
          files: |
            ./rallly-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: all
          push: true

      - name: Update version
        run: |
          echo "${{ steps.gen_meta.outputs.rallly_ver }}" > rallly_version.txt
          git config --global user.name 'rox'
          git config --global user.email 'roxedus@users.noreply.github.com'
          git add rallly_version.txt
          git commit -m "Automated bump"
          git push
