name: Check Rallly

on:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - ".github/workflows/rallly-trigger.yml"
      - ".github/workflows/rallly-bake.yml"
jobs:
  updates:
    name: Check latest version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create VARS
        run: |
          export RALLLY_VERSION=$(curl -sX GET https://api.github.com/repos/lukevella/rallly/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
          echo "${RALLLY_VERSION}"
          if  [[ $(< rallly_version.txt) != "${RALLLY_VERSION}" ]]; then
            curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/Roxedus/pipelines/actions/workflows/rallly-bake.yml/dispatches \
              -d "{\"ref\":\"refs/heads/main\", \"inputs\":{\"rallly_version\": \"${RALLLY_VERSION}\"}" \
              -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}"
          else
            echo "latest version ${RALLLY_VERSION} already built"
          fi
