name: Build traefik-cloudflare-tunnel

on:
  push:
    paths:
      - ".github/workflows/traefik-cloudflare-tunnel.yml"
      - "traefik-cloudflare-tunnel-bake.hcl"
      - "traefik-cloudflare-tunnel/**"
    branches:
      - main

jobs:
  bake-traefik-cloudflare-tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate metadata
        id: gen_meta
        run: |
          SUBMODULE=$(git submodule status traefik-cloudflare-tunnel | awk '{print substr($1,0,8);}')
          echo "**** Setting build date to $BUILD_DATE ****"
          echo ::set-output name=sub_sha::${SUBMODULE}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            ghcr.io/roxedus/pipelines
          labels: |
            org.opencontainers.image.title=traefik-cloudflare-tunnel
            org.opencontainers.image.description="https://github.com/justmiles/traefik-cloudflare-tunnel"
            org.opencontainers.image.vendor=roxedus
            org.opencontainers.image.source="https://github.com/roxedus/pipelines"
            org.opencontainers.image.version="${{ steps.gen_meta.outputs.sub_sha }}"
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.gen_meta.outputs.sub_sha }}
          flavor: |
            prefix=traefik-cloudflare-tunnel-,onlatest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: roxedus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v4.0.0
        with:
          files: |
            ./traefik-cloudflare-tunnel-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: all
          push: true
